package main // import "golang.handcraftedbits.com/ezif/cmd/genhelper"

//
// Private variables
//

var templateGroupSource = `// Code generated by ezif.  DO NOT EDIT.

// Package {{ .PackageName | LastPackage }} defines helper functions for accessing {{ .PackageDescription }}.
//
// See the Exiv2 documentation for more information: {{ .Reference }}
package {{ .PackageName | LastPackage }} // import "golang.handcraftedbits.com/ezif/helper/{{ .PackageName }}"

import (
{{- range RequiredImports .FunctionMappings false }}
	"{{ . }}"
{{ end -}}
)

{{- $disabledAccessors := .DisabledAccessors }}
{{- $familyName := .FamilyName -}}
{{- $functionMappings := .FunctionMappings }}

//
// Public functions
//

{{ range .FunctionNames }}
	{{- $functionInfo := index $functionMappings . }}
	
	{{- if IsAccessorEnabled $functionInfo $disabledAccessors }}
		// Get{{ . }} retrieves the raw value of the "{{ $functionInfo.Tag.Label }}" {{ $familyName }} metadata, ` +
	`which is described as "{{ $functionInfo.Tag.Description | FixDescription }}."  See the Exiv2 documentation ` +
	`regarding key "{{ $functionInfo.FullTagName }}" for more information.
		func Get{{ . }} (metadata ezif.ImageMetadata) ({{ GoType $familyName $functionInfo }}, bool) {
			if !metadata.{{ $familyName }}().HasKey("{{ $functionInfo.FullTagName }}") {
				return {{ DefaultValue $familyName $functionInfo }}, false
			}

			return {{ ValueFunction $familyName $functionInfo }}(metadata.{{ $familyName }}().Get("
				{{- $functionInfo.FullTagName }}")), true
		}
	{{ end -}}
{{ end -}}
`

var templateGroupTestSource = `// Code generated by ezif.  DO NOT EDIT.

package {{ .PackageName | LastPackage }} // import "golang.handcraftedbits.com/ezif/helper/{{ .PackageName }}"

import (
{{- range RequiredImports .FunctionMappings true }}
	"{{ . }}"
{{ end -}}
)

{{- $disabledAccessors := .DisabledAccessors }}
{{- $disabledTests := .DisabledTests }}
{{- $familyName := .FamilyName -}}
{{- $functionMappings := .FunctionMappings }}

//
// Public functions
//

{{ range .FunctionNames }}
	{{- $functionInfo := index $functionMappings . }}
	
	{{- if and (IsAccessorEnabled $functionInfo $disabledAccessors) (IsTestEnabled $functionInfo $disabledTests) }}
		func TestGet{{ . }} (t *testing.T) {
			var getterFunc = func (metadata ezif.ImageMetadata) (interface{}, bool) {
				return Get{{ . }}(metadata)
			}

			t.Run(internal.SubTestMaxValue, func(t *testing.T) {
				_ = internal.TestGetValueFromHelper(t, "{{ $functionInfo.FullTagName }}", getterFunc,
					{{ MaxValue $familyName $functionInfo }})
			})

			t.Run(internal.SubTestMissingValue, func(t *testing.T) {
				internal.TestGetMissingValueFromHelper(t, "{{ $functionInfo.FullTagName }}", getterFunc)
			})
		}
	{{ end -}}
{{ end -}}
`
